set_property:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: dreame_fan
    property:
      required: true
      example: "2.4"
      selector:
        text:
    value:
      required: true
      example: 8
      selector:
        number:
          min: 0
          max: 65535
          mode: box
